-- Machine-generated witness data for the 4-vertex 2-graph
-- canonicalization sweep: 64 masks, 24 permutations,
-- 11 representatives. Generated by gen_canon.py; the sweep
-- verifies it, so it carries no trust.
import LeanFlagAlgebras.BitMask.Mask2

namespace FlagAlgebras.Compute.BitMask.Canon4

/-- Canonical representative masks, one per isomorphism class. -/
def reps4 : List ℕ :=
  [0, 1, 3, 7, 11, 12, 13, 15, 30, 31, 63]

/-- The 24 packed vertex permutations (3 bits per vertex). -/
def perms4 : List ℕ :=
  [1672, 1224, 1616, 720, 1112, 664, 1665, 1217, 1553, 209, 1049, 153, 1602, 706, 1546, 202, 538,
   90, 1091, 643, 1035, 139, 531, 83]

/-- Packed rank maps (5 bits per pair position). -/
def rankMaps4 : List ℕ :=
  [172066848, 171050048, 139560961, 137527361, 106038274, 105021474, 169906272, 168889472,
   72388611, 68321411, 38865924, 35815524, 136320097, 134286497, 71308323, 67241123, 4262949,
   2229349, 101717122, 100700322, 36705348, 33654948, 3182661, 1149061]

/-- Packed witness permutation indices (5 bits per mask,
1024 masks per chunk). -/
def wChunks4 : List ℕ :=
  [
   34265786986421294835166379202160757145296216435336618066572022433387824893955746822188300240896]

end FlagAlgebras.Compute.BitMask.Canon4
