-- Machine-generated witness data for the 2-vertex 2-graph
-- canonicalization sweep: 2 masks, 2 permutations,
-- 2 representatives. Generated by gen_canon.py; the sweep
-- verifies it, so it carries no trust.
import LeanFlagAlgebras.BitMask.Mask2

namespace FlagAlgebras.Compute.BitMask.Canon2

/-- Canonical representative masks, one per isomorphism class. -/
def reps2 : List ℕ :=
  [0, 1]

/-- The 2 packed vertex permutations (3 bits per vertex). -/
def perms2 : List ℕ :=
  [8, 1]

/-- Packed rank maps (5 bits per pair position). -/
def rankMaps2 : List ℕ :=
  [0, 0]

/-- Packed witness permutation indices (3 bits per mask,
1024 masks per chunk). -/
def wChunks2 : List ℕ :=
  [0]

end FlagAlgebras.Compute.BitMask.Canon2
