-- Machine-generated witness data for the 3-vertex 2-graph
-- canonicalization sweep: 8 masks, 6 permutations,
-- 4 representatives. Generated by gen_canon.py; the sweep
-- verifies it, so it carries no trust.
import LeanFlagAlgebras.BitMask.Mask2

namespace FlagAlgebras.Compute.BitMask.Canon3

/-- Canonical representative masks, one per isomorphism class. -/
def reps3 : List ℕ :=
  [0, 1, 3, 7]

/-- The 6 packed vertex permutations (3 bits per vertex). -/
def perms3 : List ℕ :=
  [136, 80, 129, 17, 66, 10]

/-- Packed rank maps (5 bits per pair position). -/
def rankMaps3 : List ℕ :=
  [2080, 2049, 1088, 1026, 65, 34]

/-- Packed witness permutation indices (3 bits per mask,
1024 masks per chunk). -/
def wChunks3 : List ℕ :=
  [868416]

end FlagAlgebras.Compute.BitMask.Canon3
