"""Generate witness data for the 2-graph canonicalization sweeps.

For each n-vertex mask (bit pairIdx(a,b) = edge {a,b}), compute the
canonical representative (minimum image mask over all n! vertex
permutations) and a witness permutation index achieving it. Emits Lean
literals: packed permutations (3 bits/vertex), packed rank maps
(5 bits/pair position), the representative list, and packed witness
chunks. Orbit-based: each isomorphism class is processed once.

The emitted data is *untrusted* — the kernel sweep (`Canon5.lean` /
`Canon6Sweep*.lean`) verifies every claim it makes.

Usage (from the repository root):
    python LeanFlagAlgebras/BitMask/gen_canon.py 5 LeanFlagAlgebras/BitMask/Canon5Data.lean
    python LeanFlagAlgebras/BitMask/gen_canon.py 6 LeanFlagAlgebras/BitMask/Canon6Data.lean
"""
import sys
from itertools import permutations, combinations

sys.set_int_max_str_digits(1000000)

def gen(n, wbits, chunk_entries, kfix=0):
    """kfix > 0: rooted mode — canonicalize only under permutations fixing
    positions 0..kfix-1 pointwise (the σ-typed flag convention)."""
    pairs = list(combinations(range(n), 2))
    P = len(pairs)
    pidx = {p: i for i, p in enumerate(pairs)}
    perms = [w for w in permutations(range(n))
             if all(w[i] == i for i in range(kfix))]
    perm_index = {w: i for i, w in enumerate(perms)}
    nperms = len(perms)
    assert nperms < (1 << wbits)

    # position map per perm: posmap[i][rk] = pairIdx(sorted(w[a], w[b]))
    posmap = []
    for w in perms:
        pm = [0] * P
        for (a, b), rk in pidx.items():
            c, d = sorted((w[a], w[b]))
            pm[rk] = pidx[(c, d)]
        posmap.append(pm)

    def apply_pm(pm, m):
        h = 0
        rk = 0
        mm = m
        while mm:
            if mm & 1:
                h |= 1 << pm[rk]
            mm >>= 1
            rk += 1
        return h

    def inv(w):
        iw = [0] * n
        for i, v in enumerate(w):
            iw[v] = i
        return tuple(iw)

    def comp(u, w):  # (u . w)(v) = u[w[v]]
        return tuple(u[w[v]] for v in range(n))

    total = 1 << P
    witness = [None] * total
    reps = set()
    for m0 in range(total):
        if witness[m0] is not None:
            continue
        # orbit of m0
        images = [apply_pm(posmap[i], m0) for i in range(nperms)]
        rep = min(images)
        istar = images.index(rep)
        wstar = perms[istar]
        reps.add(rep)
        for i, h in enumerate(images):
            if witness[h] is None:
                # perm mapping h -> rep is wstar . inv(perms[i])
                witness[h] = perm_index[comp(wstar, inv(perms[i]))]

    reps = sorted(reps)

    # sanity: the witness rank map reproduces a listed representative
    for m in range(0, total, max(1, total // 97)):
        i = witness[m]
        h = apply_pm(posmap[i], m)
        assert h in reps, (m, i, h)

    packed_perms = [sum(w[i] << (3 * i) for i in range(n)) for w in perms]
    packed_ranks = [sum(pm[rk] << (5 * rk) for rk in range(P)) for pm in posmap]
    chunks = []
    for base in range(0, total, chunk_entries):
        c = 0
        for j in range(chunk_entries):
            if base + j < total:
                c |= witness[base + j] << (wbits * j)
        chunks.append(c)
    return P, nperms, reps, packed_perms, packed_ranks, chunks

def lean_list(name, ty, xs):
    lines = [f"def {name} : {ty} :="]
    body = []
    cur = "  ["
    for k, x in enumerate(xs):
        s = str(x) + ("," if k < len(xs) - 1 else "")
        if len(cur) + len(s) + 1 > 98:
            body.append(cur)
            cur = "   " + s
        else:
            cur = cur + (" " if cur.strip("[ ") else "") + s if cur != "  [" else cur + s
    body.append(cur + "]")
    return "\n".join(lines + body)

def emit(n, wbits, chunk_entries, out):
    P, nperms, reps, pp, pr, chunks = gen(n, wbits, chunk_entries)
    with open(out, "w", encoding="utf-8") as f:
        f.write(f"-- Machine-generated witness data for the {n}-vertex 2-graph\n")
        f.write(f"-- canonicalization sweep: {1 << P} masks, {nperms} permutations,\n")
        f.write(f"-- {len(reps)} representatives. Generated by gen_canon.py; the sweep\n")
        f.write(f"-- verifies it, so it carries no trust.\n")
        f.write("import LeanFlagAlgebras.BitMask.Mask2\n\n")
        f.write(f"namespace FlagAlgebras.Compute.BitMask.Canon{n}\n\n")
        f.write(f"/-- Canonical representative masks, one per isomorphism class. -/\n")
        f.write(lean_list(f"reps{n}", "List ℕ", reps) + "\n\n")
        f.write(f"/-- The {nperms} packed vertex permutations (3 bits per vertex). -/\n")
        f.write(lean_list(f"perms{n}", "List ℕ", pp) + "\n\n")
        f.write(f"/-- Packed rank maps (5 bits per pair position). -/\n")
        f.write(lean_list(f"rankMaps{n}", "List ℕ", pr) + "\n\n")
        f.write(f"/-- Packed witness permutation indices ({wbits} bits per mask,\n")
        f.write(f"{chunk_entries} masks per chunk). -/\n")
        f.write(lean_list(f"wChunks{n}", "List ℕ", chunks) + "\n\n")
        f.write(f"end FlagAlgebras.Compute.BitMask.Canon{n}\n")
    print(f"n={n}: P={P}, perms={nperms}, reps={len(reps)}, chunks={len(chunks)}")
    print(f"wrote {out}")

def emitRooted(k, m, wbits, chunk_entries, out):
    """Rooted-mode data for σ-typed flags with k roots on m vertices."""
    P, nperms, reps, pp, pr, chunks = gen(m, wbits, chunk_entries, kfix=k)
    tag = f"{k}_{m}"
    with open(out, "w", encoding="utf-8") as f:
        f.write(f"-- Machine-generated witness data for the rooted ({k} roots,\n")
        f.write(f"-- {m} vertices) canonicalization sweep: {1 << P} masks,\n")
        f.write(f"-- {nperms} root-fixing permutations, {len(reps)} representatives.\n")
        f.write(f"-- Generated by gen_canon.py; the sweep verifies it.\n")
        f.write("import LeanFlagAlgebras.BitMask.Mask2\n\n")
        f.write("set_option maxRecDepth 100000\n\n")
        f.write(f"namespace FlagAlgebras.Compute.BitMask.RCanon{tag}\n\n")
        f.write(f"/-- Rooted canonical representative masks. -/\n")
        f.write(lean_list(f"rreps{tag}", "List ℕ", reps) + "\n\n")
        f.write(f"/-- The {nperms} packed root-fixing permutations (3 bits per vertex). -/\n")
        f.write(lean_list(f"rperms{tag}", "List ℕ", pp) + "\n\n")
        f.write(f"/-- Packed rank maps (5 bits per pair position). -/\n")
        f.write(lean_list(f"rrankMaps{tag}", "List ℕ", pr) + "\n\n")
        f.write(f"/-- Packed witness permutation indices ({wbits} bits per mask). -/\n")
        f.write(lean_list(f"rwChunks{tag}", "List ℕ", chunks) + "\n\n")
        f.write(f"end FlagAlgebras.Compute.BitMask.RCanon{tag}\n")
    print(f"rooted k={k} m={m}: P={P}, perms={nperms}, reps={len(reps)}")
    print(f"wrote {out}")

def gen7():
    """n = 7 layout: witness entry = permIdx (13 bits) | repIdx << 13
    (24 bits/mask, 1024 masks/chunk, chunks in rows of 32); permutations
    and rank maps in rows of 30; representatives also packed 21 bits
    apiece into one natural."""
    n = 7
    pairs = list(combinations(range(n), 2))
    P = len(pairs)  # 21
    pidx = {p: i for i, p in enumerate(pairs)}
    perms = list(permutations(range(n)))  # 5040
    perm_index = {w: i for i, w in enumerate(perms)}
    nperms = len(perms)

    posmap = []
    for w in perms:
        pm = [0] * P
        for (a, b), rk in pidx.items():
            c, d = sorted((w[a], w[b]))
            pm[rk] = pidx[(c, d)]
        posmap.append(pm)

    def apply_pm(pm, m):
        h = 0
        rk = 0
        while m:
            if m & 1:
                h |= 1 << pm[rk]
            m >>= 1
            rk += 1
        return h

    def inv(w):
        iw = [0] * n
        for i, v in enumerate(w):
            iw[v] = i
        return tuple(iw)

    def comp(u, w):
        return tuple(u[w[v]] for v in range(n))

    total = 1 << P  # 2097152
    wit_perm = [None] * total
    mask_rep = [0] * total
    reps = set()
    inv_perms = [inv(w) for w in perms]
    for m0 in range(total):
        if wit_perm[m0] is not None:
            continue
        images = [apply_pm(posmap[i], m0) for i in range(nperms)]
        rep = min(images)
        wstar = perms[images.index(rep)]
        reps.add(rep)
        for i, h in enumerate(images):
            if wit_perm[h] is None:
                wit_perm[h] = perm_index[comp(wstar, inv_perms[i])]
                mask_rep[h] = rep
    reps = sorted(reps)
    rep_pos = {r: i for i, r in enumerate(reps)}
    print(f"n=7: reps={len(reps)} (expect 1044)")
    assert len(reps) == 1044

    # sanity on a sample: witness rank map reproduces the stored rep
    for m in range(0, total, total // 997):
        assert apply_pm(posmap[wit_perm[m]], m) == mask_rep[m]

    packed_perms = [sum(w[i] << (3 * i) for i in range(n)) for w in perms]
    packed_ranks = [sum(pm[rk] << (5 * rk) for rk in range(P)) for pm in posmap]
    reps_packed = sum(r << (21 * i) for i, r in enumerate(reps))

    def rows_of(xs, k):
        return [xs[i:i + k] for i in range(0, len(xs), k)]

    # 2048 chunks of 1024 entries x 24 bits, in 64 rows of 32 chunks
    chunks = []
    for base in range(0, total, 1024):
        c = 0
        for j in range(1024):
            m = base + j
            c |= (wit_perm[m] | (rep_pos[mask_rep[m]] << 13)) << (24 * j)
        chunks.append(c)
    return (packed_perms, packed_ranks, reps, reps_packed,
            rows_of(chunks, 32))

def nested_lean_list(name, rows):
    out = [f"def {name} : List (List ℕ) := ["]
    for ri, row in enumerate(rows):
        body = ",\n   ".join(str(x) for x in row)
        out.append("  [" + body + ("]," if ri < len(rows) - 1 else "]"))
    out.append("]")
    return "\n".join(out)

def emit7(outdir):
    import os
    pp, pr, reps, reps_packed, wrows = gen7()
    hdr = ("-- Machine-generated witness data for the 7-vertex 2-graph\n"
           "-- canonicalization sweep (gen_canon.py; untrusted, sweep-verified).\n"
           "import LeanFlagAlgebras.BitMask.Mask2\n\n"
           "set_option maxRecDepth 100000\n\n"
           "namespace FlagAlgebras.Compute.BitMask.Canon7\n\n")
    ftr = "\nend FlagAlgebras.Compute.BitMask.Canon7\n"
    with open(os.path.join(outdir, "Canon7DataPerms.lean"), "w", encoding="utf-8") as f:
        f.write(hdr)
        f.write("/-- The 5040 packed vertex permutations (3 bits per vertex), rows of 30. -/\n")
        f.write(nested_lean_list("perms7", [pp[i:i+30] for i in range(0, 5040, 30)]) + "\n\n")
        f.write("/-- Packed rank maps (5 bits per pair position), rows of 30. -/\n")
        f.write(nested_lean_list("rankMaps7", [pr[i:i+30] for i in range(0, 5040, 30)]) + "\n")
        f.write(ftr)
    with open(os.path.join(outdir, "Canon7DataReps.lean"), "w", encoding="utf-8") as f:
        f.write(hdr)
        f.write("/-- The 1044 canonical representative masks, one per isomorphism class. -/\n")
        f.write(lean_list("reps7", "List ℕ", reps) + "\n\n")
        f.write("/-- The representatives packed 21 bits apiece (index-aligned with `reps7`). -/\n")
        f.write(f"def repsPacked7 : ℕ :=\n  {reps_packed}\n")
        f.write(ftr)
    for k in range(8):
        with open(os.path.join(outdir, f"Canon7DataW{k}.lean"), "w", encoding="utf-8") as f:
            f.write(hdr)
            f.write(f"/-- Witness chunk rows {8*k}-{8*k+7} of 64 (24 bits per mask:\n")
            f.write("permutation index | representative index << 13; 1024 masks per\n")
            f.write("chunk, 32 chunks per row). -/\n")
            f.write(nested_lean_list(f"wRows7_{k}", wrows[8*k:8*k+8]) + "\n")
            f.write(ftr)
    with open(os.path.join(outdir, "Canon7Data.lean"), "w", encoding="utf-8") as f:
        f.write("-- Machine-generated aggregator for the 7-vertex witness data.\n")
        for k in range(8):
            f.write(f"import LeanFlagAlgebras.BitMask.Canon7DataW{k}\n")
        f.write("import LeanFlagAlgebras.BitMask.Canon7DataPerms\n")
        f.write("import LeanFlagAlgebras.BitMask.Canon7DataReps\n\n")
        f.write("namespace FlagAlgebras.Compute.BitMask.Canon7\n\n")
        f.write("/-- All 2048 witness chunks, in 64 rows of 32. -/\n")
        f.write("def wChunks7 : List (List ℕ) :=\n  ")
        f.write(" ++ ".join(f"wRows7_{k}" for k in range(8)) + "\n")
        f.write(ftr)
    print(f"wrote Canon7Data*.lean to {outdir}")

if __name__ == "__main__":
    if sys.argv[1] == "rooted":
        # gen_canon.py rooted <k> <m> <out>
        kk, mm, out = int(sys.argv[2]), int(sys.argv[3]), sys.argv[4]
        emitRooted(kk, mm, 3 if mm - kk <= 3 else 5, 1024, out)
        raise SystemExit(0)
    n = int(sys.argv[1])
    out = sys.argv[2]
    if n == 2:
        emit(2, 3, 1024, out)
    elif n == 3:
        emit(3, 3, 1024, out)
    elif n == 4:
        emit(4, 5, 1024, out)
    elif n == 5:
        emit(5, 7, 1024, out)
    elif n == 6:
        emit(6, 10, 1024, out)
    elif n == 7:
        emit7(out)
    else:
        raise SystemExit("supported: 2-7")
