-- Machine-generated witness data for the rooted (1 roots,
-- 2 vertices) canonicalization sweep: 2 masks,
-- 1 root-fixing permutations, 2 representatives.
-- Generated by gen_canon.py; the sweep verifies it.
import LeanFlagAlgebras.BitMask.Mask2

namespace FlagAlgebras.Compute.BitMask.RCanon1_2

/-- Rooted canonical representative masks. -/
def rreps1_2 : List ℕ :=
  [0, 1]

/-- The 1 packed root-fixing permutations (3 bits per vertex). -/
def rperms1_2 : List ℕ :=
  [8]

/-- Packed rank maps (5 bits per pair position). -/
def rrankMaps1_2 : List ℕ :=
  [0]

/-- Packed witness permutation indices (3 bits per mask). -/
def rwChunks1_2 : List ℕ :=
  [0]

end FlagAlgebras.Compute.BitMask.RCanon1_2
