-- Machine-generated witness data for the rooted (1 roots,
-- 3 vertices) canonicalization sweep: 8 masks,
-- 2 root-fixing permutations, 6 representatives.
-- Generated by gen_canon.py; the sweep verifies it.
import LeanFlagAlgebras.BitMask.Mask2

namespace FlagAlgebras.Compute.BitMask.RCanon1_3

/-- Rooted canonical representative masks. -/
def rreps1_3 : List ℕ :=
  [0, 1, 3, 4, 5, 7]

/-- The 2 packed root-fixing permutations (3 bits per vertex). -/
def rperms1_3 : List ℕ :=
  [136, 80]

/-- Packed rank maps (5 bits per pair position). -/
def rrankMaps1_3 : List ℕ :=
  [2080, 2049]

/-- Packed witness permutation indices (3 bits per mask). -/
def rwChunks1_3 : List ℕ :=
  [262208]

end FlagAlgebras.Compute.BitMask.RCanon1_3
