-- Machine-generated witness data for the rooted (2 roots,
-- 3 vertices) canonicalization sweep: 8 masks,
-- 1 root-fixing permutations, 8 representatives.
-- Generated by gen_canon.py; the sweep verifies it.
import LeanFlagAlgebras.BitMask.Mask2

namespace FlagAlgebras.Compute.BitMask.RCanon2_3

/-- Rooted canonical representative masks. -/
def rreps2_3 : List ℕ :=
  [0, 1, 2, 3, 4, 5, 6, 7]

/-- The 1 packed root-fixing permutations (3 bits per vertex). -/
def rperms2_3 : List ℕ :=
  [136]

/-- Packed rank maps (5 bits per pair position). -/
def rrankMaps2_3 : List ℕ :=
  [2080]

/-- Packed witness permutation indices (3 bits per mask). -/
def rwChunks2_3 : List ℕ :=
  [0]

end FlagAlgebras.Compute.BitMask.RCanon2_3
