-- Machine-generated witness data for the rooted (2 roots,
-- 4 vertices) canonicalization sweep: 64 masks,
-- 2 root-fixing permutations, 40 representatives.
-- Generated by gen_canon.py; the sweep verifies it.
import LeanFlagAlgebras.BitMask.Mask2

namespace FlagAlgebras.Compute.BitMask.RCanon2_4

/-- Rooted canonical representative masks. -/
def rreps2_4 : List ℕ :=
  [0, 1, 2, 3, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 24, 25, 26, 27, 30, 31, 32, 33, 34, 35, 38, 39,
   40, 41, 42, 43, 44, 45, 46, 47, 56, 57, 58, 59, 62, 63]

/-- The 2 packed root-fixing permutations (3 bits per vertex). -/
def rperms2_4 : List ℕ :=
  [1672, 1224]

/-- Packed rank maps (5 bits per pair position). -/
def rrankMaps2_4 : List ℕ :=
  [172066848, 171050048]

/-- Packed witness permutation indices (3 bits per mask). -/
def rwChunks2_4 : List ℕ :=
  [13792513316992550577506405271534885864355147812408692736]

end FlagAlgebras.Compute.BitMask.RCanon2_4
