-- Machine-generated witness data for the rooted (3 roots,
-- 4 vertices) canonicalization sweep: 64 masks,
-- 1 root-fixing permutations, 64 representatives.
-- Generated by gen_canon.py; the sweep verifies it.
import LeanFlagAlgebras.BitMask.Mask2

namespace FlagAlgebras.Compute.BitMask.RCanon3_4

/-- Rooted canonical representative masks. -/
def rreps3_4 : List ℕ :=
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
   26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
   50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]

/-- The 1 packed root-fixing permutations (3 bits per vertex). -/
def rperms3_4 : List ℕ :=
  [1672]

/-- Packed rank maps (5 bits per pair position). -/
def rrankMaps3_4 : List ℕ :=
  [172066848]

/-- Packed witness permutation indices (3 bits per mask). -/
def rwChunks3_4 : List ℕ :=
  [0]

end FlagAlgebras.Compute.BitMask.RCanon3_4
