import LeanFlagAlgebras.FlagAlgebra.FlagSequence
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-! # Constrained classes, the quotient algebra, and the supported space `Q_σ`

This is the Lean counterpart of paper §3.  A constraint is given by a predicate `forb`
selecting the *forbidden* `σ`-flags (those whose underlying unlabelled graph leaves the
hereditary subclass `T₁`).  We form

* the **forbidden ideal** `forbiddenIdeal forb`, generated by the forbidden flags inside
  the ambient flag algebra `A^σ[T₀] = FlagAlgebra σ`;
* the **quotient algebra** `A^σ[T₁] = ConstrainedAlgebra forb`, with quotient map
  `qmap : A^σ[T₀] →ₐ[ℝ] A^σ[T₁]`;
* the **supported space** `Q_σ = Qσ forb ⊆ X_σ`, the constrained homomorphisms, defined as
  the pullbacks `ψ ∘ qmap` of positive homomorphisms `ψ` of the quotient.

The headline §3 result is the *intrinsic description* `mem_Qσ_iff`: a homomorphism lies in
`Q_σ` iff it vanishes on every forbidden flag.  The substantive (backward) direction is the
universal property of the quotient: a ring homomorphism vanishing on the generators vanishes
on the whole ideal (its kernel is automatically an ideal), so it factors through `qmap`.
We also record that `Q_σ` is closed (`Qσ_isClosed`).
-/

namespace FlagAlgebras.MetaTheory

variable {n₀ : ℕ} {σ : FlagType (Fin n₀)}

/-- The ideal of the ambient flag algebra generated by the forbidden flags. -/
def forbiddenIdeal (forb : FinFlag σ → Prop) : Ideal (FlagAlgebra σ) :=
  Ideal.span {x : FlagAlgebra σ | ∃ F, forb F ∧ x = ⟦basisVector F⟧}

/-- The quotient ("constrained") flag algebra `A^σ[T₁] = A^σ[T₀] / (forbidden flags)`. -/
abbrev ConstrainedAlgebra (forb : FinFlag σ → Prop) : Type :=
  FlagAlgebra σ ⧸ forbiddenIdeal forb

/-- The quotient map `A^σ[T₀] ↠ A^σ[T₁]`, an `ℝ`-algebra homomorphism. -/
noncomputable def qmap (forb : FinFlag σ → Prop) :
    FlagAlgebra σ →ₐ[ℝ] ConstrainedAlgebra forb :=
  Ideal.Quotient.mkₐ ℝ (forbiddenIdeal forb)

/-- `qmap` kills every forbidden flag. -/
lemma qmap_basisVector_forbidden {forb : FinFlag σ → Prop} {F : FinFlag σ} (hF : forb F) :
    qmap forb (⟦basisVector F⟧ : FlagAlgebra σ) = 0 := by
  show Ideal.Quotient.mkₐ ℝ (forbiddenIdeal forb) ⟦basisVector F⟧ = 0
  rw [Ideal.Quotient.mkₐ_eq_mk]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span ⟨F, hF, rfl⟩)

/-- The constrained (`T₁`-supported) part of the ambient homomorphism space `X_σ`: the
density profiles arising from a positive homomorphism of the quotient algebra. -/
def Qσ (forb : FinFlag σ → Prop) : Set (PositiveHomSpace σ) :=
  {χ | ∃ ψ : ConstrainedAlgebra forb →ₐ[ℝ] ℝ,
        (∀ F : FinFlag σ, 0 ≤ ψ (qmap forb ⟦basisVector F⟧)) ∧
        (∀ F : FinFlag σ, χ.val F = ψ (qmap forb ⟦basisVector F⟧))}

/-- **Intrinsic description of `Q_σ`** (paper §3): a homomorphism is constrained iff it
vanishes on every forbidden flag.  The forward direction is immediate; the backward
direction factors the homomorphism through the quotient via its (automatically ideal)
kernel. -/
theorem mem_Qσ_iff (forb : FinFlag σ → Prop) (χ : PositiveHomSpace σ) :
    χ ∈ Qσ forb ↔ ∀ F : FinFlag σ, forb F → χ.val F = 0 := by
  constructor
  · rintro ⟨ψ, _, hval⟩ F hF
    rw [hval F, qmap_basisVector_forbidden hF, map_zero]
  · intro hforb
    -- the recovered homomorphism, as an algebra map `A^σ[T₀] → ℝ`
    set f : FlagAlgebra σ →ₐ[ℝ] ℝ := (PositiveHomSpace.toPosHom χ).val
    have hf_basis : ∀ F : FinFlag σ, f ⟦basisVector F⟧ = χ.val F := fun F =>
      PositiveHomSpace.toPosHom_basisVector χ F
    -- the forbidden ideal lies in the kernel of `f`
    have hker : ∀ a ∈ forbiddenIdeal forb, f a = 0 := by
      have hle : forbiddenIdeal forb ≤ RingHom.ker (f : FlagAlgebra σ →+* ℝ) := by
        apply Ideal.span_le.mpr
        rintro x ⟨F, hF, rfl⟩
        simp only [SetLike.mem_coe, RingHom.mem_ker]
        show f ⟦basisVector F⟧ = 0
        rw [hf_basis F]; exact hforb F hF
      intro a ha
      have := hle ha
      rwa [RingHom.mem_ker] at this
    -- factor `f` through the quotient
    refine ⟨Ideal.Quotient.liftₐ (forbiddenIdeal forb) f hker, ?_, ?_⟩
    · intro F
      have hcomp : Ideal.Quotient.liftₐ (forbiddenIdeal forb) f hker (qmap forb ⟦basisVector F⟧)
          = f ⟦basisVector F⟧ :=
        DFunLike.congr_fun (Ideal.Quotient.liftₐ_comp (forbiddenIdeal forb) f hker) _
      rw [hcomp, hf_basis F]
      exact PositiveHomSpace.toPosHom_basisVector χ F ▸ positiveHom_basisVector_ge_zero _ F
    · intro F
      have hcomp : Ideal.Quotient.liftₐ (forbiddenIdeal forb) f hker (qmap forb ⟦basisVector F⟧)
          = f ⟦basisVector F⟧ :=
        DFunLike.congr_fun (Ideal.Quotient.liftₐ_comp (forbiddenIdeal forb) f hker) _
      rw [hcomp, hf_basis F]

/-- `Q_σ` is closed in `X_σ` (an intersection of zero-sets of continuous evaluations). -/
theorem Qσ_isClosed (forb : FinFlag σ → Prop) : IsClosed (Qσ forb) := by
  have hset : Qσ forb = ⋂ (F : FinFlag σ) (_ : forb F),
      {χ : PositiveHomSpace σ | χ.val F = 0} := by
    ext χ
    simp only [Set.mem_iInter, Set.mem_setOf_eq, mem_Qσ_iff forb χ]
  rw [hset]
  refine isClosed_iInter fun F => isClosed_iInter fun _ => ?_
  exact isClosed_eq ((FinFlag.continuous F).comp continuous_subtype_val) continuous_const

end FlagAlgebras.MetaTheory
